spring:
  datasource:
    dirver-class-name: com.mysql.cj.jdbc.Driver
    url :  jdbc:mysql://localhost:3306/hitechautoworks
    username: ohgiraffers
    password: ohgiraffers
  mail:
    host: smtp.gmail.com
    port: 587
    username: realyoon77@gmail.com
    password: qmrboharwfjphgzb
    properties:
      mail:
        smtp:
          auth: true
          timeout: 25000
          starttls:
            enable: true
        protocol: smtp
mybatis:
  mapper-locations: mapper/**/*.xml

