spring:
  datasource:
    dirver-class-name: com.mysql.cj.jdbc.Driver
    url :  jdbc:mysql://115.95.149.11:3306/hitechautoworks
    username: 
    password: 
  mail:
    host: smtp.gmail.com
    port: 587
    username: realyoon77@gmail.com
    password: 
    properties:
      mail:
        smtp:
          auth: true
          timeout: 25000
          starttls:
            enable: true
        protocol: smtp
mybatis:
  mapper-locations: mapper/**/*.xml
server:
  port: 80

coolsms:
  api:
    key: 
    secret:
file:
  upload-dir: ${user.home}/app/images/profile
logging:
  file:
    name: ${user.dir}/log/notepad.log
